# http://docs.travis-ci.com/user/build-configuration/

language: python

python:
    - "3.4"

sudo: false

install:
    - pip install --upgrade pip
    - pip --version
    - pip install Flask
    - pip install Flask-Script
    - pip install Flask-SQLAlchemy
    - pip install Flask-Testing
    - pip install marshmallow
    - pip install flask-jsontools
    - pip install psycopg2
    - pip install requests
    - sudo apt-get install postgresql

before_script:
    - uname -a
    - printenv
    - pip list

script:
    - date
    - ls -al
    - make models.html
    - make test
    - make check