FORMAT: 1A
HOST: http://dcdatabase.me/

# DC Database API

DC comics API. A collection of character, team, comic, movie, show, and creator information.

## All Characters [/characters.json]
Affiliation refers to the teams the character is/was a member of
Links to Teams and Characters
### List All Characters [GET]

+ Response 200 (application/json)

        [
            {
                "affiliation": [
                "Justice 9"
                ], 
                "aliases": [
                "Blackbird"
                ], 
                "alignment": "Good", 
                "creators": [
                "Evan Shaner", 
                "Grant Morrison"
                ], 
                "debut": "2015", 
                "gender": "Female", 
                "identity": "Secret Identity", 
                "image": "http://vignette2.wikia.nocookie.net/marvel_dc/images/5/54/Blackbird_%28Earth_36%29.jpg/revision/latest?cb=20150222071100", 
                "real_name": "Unknown", 
                "title": "Blackbird (Earth 36)", 
                "universes": [
                "Earth 36"
                ]
            }, 
            {
                "affiliation": [
                "Sinestro Corps (Prime Earth)"
                ], 
                "aliases": [
                "Hellblazer", 
                "Yellow Lantern"
                ], 
                "alignment": "Good", 
                "creators": [
                "Steve Bissette", 
                "Alan Moore"
                ], 
                "debut": "2011", 
                "gender": "Male", 
                "identity": "Public Identity", 
                "image": "http://vignette2.wikia.nocookie.net/marvel_dc/images/a/a8/Constantine_Vol_1_1_Textless.jpg/revision/latest?cb=20130612164926", 
                "real_name": "John Constantine", 
                "title": "John Constantine (Prime Earth)", 
                "universes": [
                "Prime Earth"
                ]
            }, 
            {
                "affiliation": [
                "The Green"
                ], 
                "aliases": [
                "Poison Ivy", 
                "Poison Ice"
                ], 
                "alignment": "Neutral", 
                "creators": [
                "Sheldon Moldoff", 
                "Robert Kanigher"
                ], 
                "debut": "2011", 
                "gender": "Female", 
                "identity": "Secret Identity", 
                "image": "http://vignette3.wikia.nocookie.net/marvel_dc/images/1/1e/Detective_Comics_Vol_2_23.1_Poison_Ivy_Textless.jpg/revision/latest?cb=20130904205517", 
                "real_name": "Pamela Isley", 
                "title": "Pamela Isley (Prime Earth)", 
                "universes": [
                "Prime Earth"
                ]
            }
        ]


## Character [/characters/{title}.json]
A single Character with all its details. 

+ Parameters
    + title (string) - title of a character
    

### Retrieve a Character [GET]
+ Response 200 (application/json)
    

    + Body
    
            {
                "affiliation": [
                "The Green"
                ], 
                "aliases": [
                "Poison Ivy", 
                "Poison Ice"
                ], 
                "alignment": "Neutral", 
                "creators": [
                "Sheldon Moldoff", 
                "Robert Kanigher"
                ], 
                "debut": "2011", 
                "gender": "Female", 
                "identity": "Secret Identity", 
                "image": "http://vignette3.wikia.nocookie.net/marvel_dc/images/1/1e/Detective_Comics_Vol_2_23.1_Poison_Ivy_Textless.jpg/revision/latest?cb=20130904205517", 
                "real_name": "Pamela Isley", 
                "title": "Pamela Isley (Prime Earth)", 
                "universes": [
                "Prime Earth"
                ]
            }



## All Teams [/teams.json]
Links to Characters and Comics
### List All Teams [GET]

+ Response 200 (application/json)

        [
            {
                "creators": [
                "Bernie Wrightson", 
                "Jim Starlin"
                ], 
                "debut": "1988", 
                "enemies": [
                "Blood Tribe", 
                "Vandal Savage"
                ], 
                "identity": "Secret", 
                "image": "http://vignette1.wikia.nocookie.net/marvel_dc/images/d/d7/Miagani_001.jpg/revision/latest?cb=20150206210100", 
                "status": "Defunct", 
                "team_leaders": [], 
                "title": "Miagani", 
                "universes": [
                "New Earth", 
                "Prime Earth"
                ]
            }, 
            {
                "creators": [
                "Ivan Reis", 
                "Grant Morrison", 
                "Trivia"
                ], 
                "debut": "2014", 
                "enemies": [
                "Justice Incarnate"
                ], 
                "identity": "Public", 
                "image": "http://vignette4.wikia.nocookie.net/marvel_dc/images/1/1c/The_Gentry_0001.jpg/revision/latest?cb=20150218003531", 
                "status": "Active", 
                "team_leaders": [
                "Empty Hand"
                ], 
                "title": "The Gentry", 
                "universes": [
                "Not available"
                ]
            }, 
            {
                "creators": [
                "Jes\u00fas Sa\u00edz", 
                "Greg Rucka"
                ], 
                "debut": "2005", 
                "enemies": [
                "Metahumans"
                ], 
                "identity": "Public", 
                "image": "http://vignette1.wikia.nocookie.net/marvel_dc/images/3/3a/OMAC_01.JPG/revision/latest?cb=20151020170952", 
                "status": "Defunct", 
                "team_leaders": [
                "Brother Eye"
                ], 
                "title": "Omni Mind and Community", 
                "universes": [
                "New Earth"
                ]
            }
        ]
        
## Team [/teams/{title}.json]
A single Team with all its details. 

+ Parameters
    + title (string) - name of a team
    

### Retrieve a Team [GET]
+ Response 200 (application/json)
    

    + Body
    
            {
                "creators": [
                "Jes\u00fas Sa\u00edz", 
                "Greg Rucka"
                ], 
                "debut": "2005", 
                "enemies": [
                "Metahumans"
                ], 
                "identity": "Public", 
                "image": "http://vignette1.wikia.nocookie.net/marvel_dc/images/3/3a/OMAC_01.JPG/revision/latest?cb=20151020170952", 
                "status": "Defunct", 
                "team_leaders": [
                "Brother Eye"
                ], 
                "title": "Omni Mind and Community", 
                "universes": [
                "New Earth"
                ]
            }


## All Comics [/comics.json]
Links to Characters and Creators
### List All Comics [GET]

+ Response 200 (application/json)

        [
            {
                "creators": [
                  "Sal Cipriano", 
                  "Francis Manapul", 
                  "Geoff Johns", 
                  "Scott Kolins", 
                  "Michael Atiyeh"
                ], 
                "featured_characters": [
                  "Bartholomew Allen (New Earth)"
                ], 
                "image": "http://vignette2.wikia.nocookie.net/marvel_dc/images/f/f5/Flash_Vol_3_12.jpg/revision/latest?cb=20110511180423", 
                "locations": [
                  "Central City"
                ], 
                "release_date": "Not available", 
                "title": "Flash Vol 3 12"
            }, 
            {
                "creators": [
                  "Brittany Holzherr", 
                  "Evan Shaner", 
                  "Jeff Parker", 
                  "Evan Shaner &#32", 
                  "(pg. 1-13)", 
                  "Jordie Bellaire", 
                  "Dave Lamphear"
                ], 
                "featured_characters": [], 
                "image": "http://vignette2.wikia.nocookie.net/marvel_dc/images/7/7c/Future_Quest_Vol_1_2.jpg/revision/latest?cb=20160707184748", 
                "locations": [], 
                "release_date": "September 2016", 
                "title": "Future Quest Vol 1 2"
            }, 
            {
                "creators": [
                  "Andrew Marino", 
                  "Martin Coccolo", 
                  "Cullen Bunn", 
                  "Blond", 
                  "Dave Sharpe"
                ], 
                "featured_characters": [
                  "Thaal Sinestro (New Earth)"
                ], 
                "image": "http://vignette3.wikia.nocookie.net/marvel_dc/images/d/d9/Sinestro_Vol_1_23.jpg/revision/latest?cb=20160519194012", 
                "locations": [
                  "Necropolis"
                ], 
                "release_date": "July 2016", 
                "title": "Sinestro Vol 1 23"
            }
        ]

## Comic [/comics/{title}.json]
A single Comic with all its details. 

+ Parameters
    + title (string) - name of a team
    

### Retrieve a Comic [GET]
+ Response 200 (application/json)
    

    + Body
    
            {
                "creators": [
                  "Andrew Marino", 
                  "Martin Coccolo", 
                  "Cullen Bunn", 
                  "Blond", 
                  "Dave Sharpe"
                ], 
                "featured_characters": [
                  "Thaal Sinestro (New Earth)"
                ], 
                "image": "http://vignette3.wikia.nocookie.net/marvel_dc/images/d/d9/Sinestro_Vol_1_23.jpg/revision/latest?cb=20160519194012", 
                "locations": [
                  "Necropolis"
                ], 
                "release_date": "July 2016", 
                "title": "Sinestro Vol 1 23"
            }

        
## All Movies [/movies.json]
Links to Characters and Creators
### List All Movies [GET]

+ Response 200 (application/json)

        [
            {
                "budget": "Not available", 
                "creators": [
                  "Dan Lin", 
                  "Roy Lee", 
                  "Phil Lord", 
                  "Christopher Miller", 
                  "Chris McKay"
                ], 
                "featured_characters": [
                  "Bruce Wayne (Lego Batman)"
                ], 
                "image": "http://vignette4.wikia.nocookie.net/marvel_dc/images/e/e8/Thelegobatmanmovieposter2017.jpg/revision/latest?cb=20160328181535", 
                "release_date": "February 10 2017", 
                "running_time": "Not available", 
                "title": "The Lego Batman Movie"
            }, 
            {
                "budget": "Not available", 
                "creators": [
                  "Randy Rogel", 
                  "Boyd Kirkland", 
                  "Benjamin Melniker", 
                  "Michael Uslan", 
                  "Distributors"
                ], 
                "featured_characters": [
                  "Bruce Wayne (DCAU)"
                ], 
                "image": "http://vignette1.wikia.nocookie.net/marvel_dc/images/2/26/Batman_and_Mr._Freeze_-_Sub-Zero.jpg/revision/latest?cb=20081021212649", 
                "release_date": "March 17 1998", 
                "running_time": "70 min", 
                "title": "Batman & Mr. Freeze: SubZero (Movie)"
            }, 
            {
                "budget": "Not available", 
                "creators": [
                  "Craig Paulsen", 
                  "Brandon Vietti", 
                  "Sam Register", 
                  "Michael Jelenic", 
                  "Editors"
                ], 
                "featured_characters": [
                  "Justice League (Lego Batman)", 
                  "Bruce Wayne (Lego Batman)", 
                  "Victor Stone (Lego Batman)", 
                  "Bartholomew Allen (Lego Batman)", 
                  "Oliver Queen (Lego Batman)", 
                  "Guy Gardner (Lego Batman)", 
                  "Hawkman (Lego Batman)", 
                  "Patrick O%27Brian (Lego Batman)", 
                  "Kal-El (Lego Batman)", 
                  "Diana of Themyscira (Lego Batman)"
                ], 
                "image": "http://vignette3.wikia.nocookie.net/marvel_dc/images/e/ef/LEGO_Justice_League_vs_Bizarro_League_covers_01.jpg/revision/latest?cb=20150124043910", 
                "release_date": "February 10  2015", 
                "running_time": "Not available", 
                "title": "Lego DC Comics Super Heroes: Justice League vs. Bizarro League (Movie)"
            }
        ]

## Movie [/movies/{title}.json]
A single Movie with all its details. 

+ Parameters
    + title (string) - name of a movie
    

### Retrieve a Movie [GET]
+ Response 200 (application/json)
    

    + Body
    
            {
                "budget": "Not available", 
                "creators": [
                  "Craig Paulsen", 
                  "Brandon Vietti", 
                  "Sam Register", 
                  "Michael Jelenic", 
                  "Editors"
                ], 
                "featured_characters": [
                  "Justice League (Lego Batman)", 
                  "Bruce Wayne (Lego Batman)", 
                  "Victor Stone (Lego Batman)", 
                  "Bartholomew Allen (Lego Batman)", 
                  "Oliver Queen (Lego Batman)", 
                  "Guy Gardner (Lego Batman)", 
                  "Hawkman (Lego Batman)", 
                  "Patrick O%27Brian (Lego Batman)", 
                  "Kal-El (Lego Batman)", 
                  "Diana of Themyscira (Lego Batman)"
                ], 
                "image": "http://vignette3.wikia.nocookie.net/marvel_dc/images/e/ef/LEGO_Justice_League_vs_Bizarro_League_covers_01.jpg/revision/latest?cb=20150124043910", 
                "release_date": "February 10  2015", 
                "running_time": "Not available", 
                "title": "Lego DC Comics Super Heroes: Justice League vs. Bizarro League (Movie)"
            }


        
## All Television Series [/shows.json]
Links to Characters and Creators
### List All TV Shows [GET]

+ Response 200 (application/json)

        [
                {
                "creators": [
                  "Max Fleischer", 
                  "Dave Fleischer", 
                  "Sam Buchwald"
                ], 
                "featured_characters": [
                  "Superman", 
                  "Lois Lane", 
                  "Perry White"
                ], 
                "first_air_date": "1941", 
                "image": "http://vignette1.wikia.nocookie.net/marvel_dc/images/4/40/Clark_Kent_1941_Superman_Cartoons_001.jpg/revision/latest?cb=20151128153001", 
                "last_air_date": "1943", 
                "running_time": "Not available", 
                "title": "Superman (1941 Cartoons)"
            }, 
            {
                "creators": [
                  "Robert Goodman", 
                  "Liz Holzman", 
                  "Jean MacCurdy", 
                  "Alan Burnett"
                ], 
                "featured_characters": [
                  "Zeta", 
                  "Ro", 
                  "Agent Bennet", 
                  "Agent West", 
                  "Agent Lee"
                ], 
                "first_air_date": "January 27 2001", 
                "image": "http://vignette2.wikia.nocookie.net/marvel_dc/images/7/70/The_Zeta_Project_series_logo.jpg/revision/latest?cb=20091129162915", 
                "last_air_date": "August 17 2002", 
                "running_time": "Not available", 
                "title": "Zeta Project (TV Series)"
            }, 
            {
                "creators": [], 
                "featured_characters": [
                  "Wonder Woman", 
                  "Harley Quinn", 
                  "Bumblebee", 
                  "Supergirl", 
                  "Poison Ivy", 
                  "Katana", 
                  "Batgirl"
                ], 
                "first_air_date": "October 1 2015", 
                "image": "http://vignette3.wikia.nocookie.net/marvel_dc/images/c/cd/DC_Super_Hero_Girls_0001.jpg/revision/latest?cb=20151002163402", 
                "last_air_date": "Not available", 
                "running_time": "Not available", 
                "title": "DC Super Hero Girls (Shorts)"
            }
        ]
        

## TV Show [/shows/{title}.json]
A single Show with all its details. 

+ Parameters
    + title (string) - name of a show
    

### Retrieve a Show [GET]
+ Response 200 (application/json)
    

    + Body
    
            {
                "creators": [], 
                "featured_characters": [
                  "Wonder Woman", 
                  "Harley Quinn", 
                  "Bumblebee", 
                  "Supergirl", 
                  "Poison Ivy", 
                  "Katana", 
                  "Batgirl"
                ], 
                "first_air_date": "October 1 2015", 
                "image": "http://vignette3.wikia.nocookie.net/marvel_dc/images/c/cd/DC_Super_Hero_Girls_0001.jpg/revision/latest?cb=20151002163402", 
                "last_air_date": "Not available", 
                "running_time": "Not available", 
                "title": "DC Super Hero Girls (Shorts)"
            }


## All Creators [/creators.json]
Links to Characters, Comics/Movies/Shows
### List All Creators [GET]
Should include writers, directors, screenwriters and the like
+ Response 200 (application/json)

        [
            {
                "birth_date": "March 16 1961", 
                "creations": [
                  "Blasters", 
                  "Chroma", 
                  "Mekanique", 
                  "Mister Bones (co-creator)"
                ], 
                "employers": [
                  "DC Comics", 
                  "Image Comics", 
                  "Marvel Comics", 
                  "McFarlane Productions"
                ], 
                "first_publication": "Infinity Inc. #14", 
                "gender": "Male", 
                "image": "http://vignette4.wikia.nocookie.net/marvel_dc/images/6/69/Todd_McFarlane.jpg/revision/latest?cb=20080110204414", 
                "job_titles": [
                  "Penciler", 
                  "Inker"
                ], 
                "title": "Todd McFarlane"
            }, 
            {
                "birth_date": "Not available", 
                "creations": [
                  "Not available"
                ], 
                "employers": [
                  "DC Comics", 
                  "Warner Bros. Entertainment", 
                  "Inc."
                ], 
                "first_publication": "Batman (2004 TV Series) Episode: Traction", 
                "gender": "Male", 
                "image": "Not available", 
                "job_titles": [
                  "Director"
                ], 
                "title": "Sam Liu"
            }, 
            {
                "birth_date": "Not available", 
                "creations": [
                  "Not available"
                ], 
                "employers": [
                  "DC Comics", 
                  "Marvel Comics", 
                  "WildStorm Productions", 
                  "Dark Horse Comics", 
                  "Image Comics"
                ], 
                "first_publication": "Superman/Batman #37", 
                "gender": "Male", 
                "image": "Not available", 
                "job_titles": [
                  "Penciler", 
                  "Inker", 
                  "Colourist", 
                  "Cover Artist", 
                  "Writer"
                ], 
                "title": "Derek Fridolfs"
            }
        ]

## Creator [/creators/{title}.json]
A single Creator with all its details. 

+ Parameters
    + title (string) - name of a creator
    

### Retrieve a Creator [GET]
+ Response 200 (application/json)
    

    + Body
    
            {
                "birth_date": "Not available", 
                "creations": [
                  "Not available"
                ], 
                "employers": [
                  "DC Comics", 
                  "Marvel Comics", 
                  "WildStorm Productions", 
                  "Dark Horse Comics", 
                  "Image Comics"
                ], 
                "first_publication": "Superman/Batman #37", 
                "gender": "Male", 
                "image": "Not available", 
                "job_titles": [
                  "Penciler", 
                  "Inker", 
                  "Colourist", 
                  "Cover Artist", 
                  "Writer"
                ], 
                "title": "Derek Fridolfs"
            }